settings:
  #system: "windows"
  webLauncher: "firefox"
  sshLauncher: "windowsTerminal"
config:
#  firefox:
#    path: "C:/Program Files/Mozilla Firefox/firefox.exe"
#    args: "--new-window"
  firefox:
<<<<<<< HEAD:serverinterface/interfaceLaunchers/launcherConfig.yaml
    path: firefox
    args: "" # -new-window is the default
=======
    #path: "C:/Program Files/Mozilla Firefox/firefox.exe"
    path: "firefox"
    args: "--new-window"
>>>>>>> e348064598b0e260f852bfc3e8c86b55c8c49dcb:serverinterface/interactions/interfaces/launcherConfig.yaml
  chrome:
    path: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
    args: "--new-window"
  edge:
    path: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
    args: "--new-window"
  ie:
    path: "C:/Program Files/Internet Explorer/iexplore.exe"
    args: "--new-window"
  opera:
    path: "C:/Program Files/Opera/launcher.exe"
    args: "--new-window"
  safari:
    path: "C:/Program Files/Safari/Safari.exe"
    args: "--new-window"
  vivaldi:
    path: "C:/Program Files/Vivaldi/Application/vivaldi.exe"
    args: "--new-window"
  windowsTerminal:
    path: "wt"
    args: "" # -d . is the default directory
<<<<<<< HEAD:serverinterface/interfaceLaunchers/launcherConfig.yaml
=======
  wslTerminal:
    path: "wsl"
    args: ""
>>>>>>> e348064598b0e260f852bfc3e8c86b55c8c49dcb:serverinterface/interactions/interfaces/launcherConfig.yaml
